_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
backbone:
    value: efficientnet_b0
batch_size:
    value: 32
data_csv:
    value: metadata_train.json
dropout:
    value: 0.2
epochs:
    value: 10
frames_dir:
    value: .\data\frames\train
lr:
    value: 0.001
output:
    value: outputs
seed:
    value: 42
